### ISSUE TITLE
follow icons / params.social

### ISSUE THREAD

**Issue by whanley** [themefisher/parsa-hugo#41]
The follow icons in the footer of my [parsa page](https://willhanley.net/) don't link to the urls I've specified in `[[params.social]]` in the [config file](https://github.com/whanley/website/blob/gh-pages/config.toml). Any suggestions?

**Comment by somratpro** [comment]
Hello @whanley 

Please use the latest version of our theme. we fixed it in the last commit. thank you

**Comment by dymn** [comment]
The problem is not solved. Even on your demo site, the link to the FB does not work. Please check it.
